dist: xenial
language: node_js
node_js:
- 6.11.3
cache:
  directories:
  - node_modules # NPM packages
install:
- npm install
script:
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_22d1f22872be_key -iv $encrypted_22d1f22872be_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
